name: 'Download File'

description: 'Downloads a file - supports all platforms'

inputs:
  url:
    description: 'The url to download the file from'
    required: true
  target:
    description: 'The target location to output the file to'
    required: false
    default: ''

runs:
  using: "composite"
  steps:

    - id: install-wget
      if: ${{ runner.os == 'Windows'}}
      run: choco install wget --no-progress
      shell: bash

    - if: ${{ failure() && runner.os == 'Windows' }}
      run: cat C:\ProgramData\chocolatey\logs\chocolatey.log
      shell: bash

    - run: >
        wget
        '${{ inputs.url }}'
        ${{ inputs.target && ('-O \'${{ inputs.target }}\'') }}
        --retry-connrefused
        --tries=3
        --no-dns-cache
        --progress=bar:force:noscroll
        --verbose
      shell: bash
